### ISSUE TITLE
query to study ALM Integration

### ISSUE THREAD

**Issue by up987up** [macroking/ALM-Integration#2]
Hi I am new in coding python, While running below code from command line as per instruction 
1. I am getting error for requests.auth import HTTPBasicAuth import requests
2. When I comment above line and run the code it's ask for parameters , what parameters should i pass 
3. what all i require to study this system.

**Comment by aarts4** [comment]
Hi ,
requests module is not installed , pls install this module using pip or easy_install.exe..
Hope this helps.

**Comment by macroking** [comment]
closing this issue
