### ISSUE TITLE
Hi Macroking, this tool is really helpful. I am wondering if you have any plans to convert to python3.9?

### ISSUE THREAD

**Issue by PavanMudigonda** [macroking/ALM-Integration#3]

**Comment by macroking** [comment]
Glad! I could help. I have not thought about upgrading it to the latest Python version, if you think it would benefit. I will certainly update it. 

Do you see any gap in this tool which I can address during the upgrade process?

**Comment by PavanMudigonda** [comment]
Hi, It would you nice to see if it can upload junit XML from cypress-Junit-reporter and if it can upload JSON files and cucumber  HTML reporter from cypress-multi-reporter. 

Also could you add instruction on how to call these functions to trigger the upload process. I am trying to use Micro Focus plugin for now to upload junit results but couldn't find a way to upload  attachments but your scripts seems nice and and it's a good way to learn python. For me.
